const A = "Hola";
let B = " mundo!";
document.write("Constante A contiene " + A );
document.write("</br>");
document.write("Variable B contiene " + B );
document.write("</br>");
document.write(A + B );
document.write("</br>");
document.write("La etiqueta BR es un salto de linea");
document.write("</br>");
document.write("El signo '+' sirve para concatenar cadenas de texto");